### ISSUE TITLE
Bad file descriptor (Errno::EBADF) - When loading with middleman s

### ISSUE THREAD

**Issue by bencalegari** [vocino/middleman-foundation#5]
```
== The Middleman is loading
== LiveReload is waiting for a browser to connect
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-fsevent-0.9.2/lib/rb-fsevent/fsevent.rb:40:in `select': Bad file descriptor       (Errno::EBADF)
```

That's what seems to be happening for me. Seen this before?

**Comment by schybo** [comment]
Did you update bundle?

I had forgotten to and got similar errors. That fixed everything up.

**Comment by bencalegari** [comment]
I forgot I posted this issue and deleted that project to start another one, which was my mistake. That could have definitely been the issue so unless I get it again I'll just close it for now.

**Comment by realpsyence** [comment]
For posterity - on a recent install I had this error until I ran 'bundle update' - seems to be OK now.

**Comment by vocino** [comment]
I should probably update the gemfile to use the default middleman installed version.
