### ISSUE TITLE
Middleman build errors on Stylesheets

### ISSUE THREAD

**Issue by martinchooooooo** [vocino/middleman-foundation#6]
Hi!

I followed the instructions in the readme and created a my_new_project
Then I ran the following commands
`bundle install`
`bundle exec middleman build`

then got the following:

```
      create  build/javascripts/vendor/jquery.js
      create  build/javascripts/foundation/foundation.placeholder.js
       error  build/stylesheets/foundation.css
       error  build/stylesheets/normalize.css
There were errors during this build, re-run with --verbose to see the full exception.
```

So i ran it again with `--verbose` but didn't get anything useful.

I then tried something I had briefly read in the Middleman docs, which was to rename the two offending stylesheets (foundation.css and normalize.css) to `.css.scss`

All worked fine afterwards.

On a slightly different note, I'm also getting a warning in the build proces
`== Unknown Extension: livereload`

**Comment by vocino** [comment]
This was being caused by having `activate :livereload` in config.rb.  Simply comment that out.
